data:
   root_dir: "artifacts/"
   pdf_directory: "artifacts/data/pdfs/"
   source_url:
    # üìò Constitution of India
    - "https://lddashboard.legislative.gov.in/sites/default/files/coi/COI_2024.pdf"

    # ‚öñÔ∏è Indian Penal Code (IPC)
    - "https://www.indiacode.nic.in/repealedfileopen?rfilename=A1860-45.pdf"

    # üïµÔ∏è Criminal Laws
    - "https://www.indiacode.nic.in/bitstream/123456789/15272/1/the_code_of_criminal_procedure,_1973.pdf"
    - "https://www.mha.gov.in/sites/default/files/250883_english_01042024.pdf"
    - "https://www.mha.gov.in/sites/default/files/250882_english_01042024.pdf"
    - "https://www.mha.gov.in/sites/default/files/2024-04/250884_2_english_01042024.pdf"

    # üßæ Civil Laws
    - "https://www.indiacode.nic.in/bitstream/123456789/11087/1/the_code_of_civil_procedure%2C_1908.pdf"

    # üß† Indian Evidence Act
    - "https://www.indiacode.nic.in/bitstream/123456789/15351/1/iea_1872.pdf"

    # üè† Registration, Property, Family Laws
    - "https://www.indiacode.nic.in/bitstream/123456789/1565/5/A1963-36.pdf"
    - "https://www.indiacode.nic.in/bitstream/123456789/15937/1/the_registration_act%2C1908.pdf"
    - "https://www.indiacode.nic.in/bitstream/123456789/2338/1/A1882-04.pdf"
    - "https://www.indiacode.nic.in/bitstream/123456789/2187/2/A187209.pdf"
    - "https://www.indiacode.nic.in/bitstream/123456789/1885/1/A194910.pdf"
    - "https://www.indiacode.nic.in/bitstream/123456789/2189/1/a1881-26.pdf"

    # üí∞ Financial & Corporate Laws
    - "https://www.indiacode.nic.in/bitstream/123456789/1988/1/A1999_42.pdf"
    - "https://www.indiacode.nic.in/bitstream/123456789/2036/5/A2003-15.pdf"
    - "https://www.indiacode.nic.in/bitstream/123456789/2114/5/A2013-18.pdf"
    - "https://www.indiacode.nic.in/bitstream/123456789/1234/1/A1961-43.pdf"

    # üíµ GST Laws
    - "https://cbic-gst.gov.in/CGST_Act_2017.pdf"
    - "https://cbic-gst.gov.in/IGST_Act_2017.pdf"

    # üó≥Ô∏è Election Laws
    - "https://www.indiacode.nic.in/bitstream/123456789/11219/1/A1950-43.pdf"
    - "https://www.indiacode.nic.in/bitstream/123456789/11220/1/A1951-43.pdf"

    # üë®‚Äçüë©‚Äçüëß Personal Laws & Social Acts
    - "https://www.indiacode.nic.in/bitstream/123456789/1569/1/A1988-49.pdf"
    - "https://www.indiacode.nic.in/bitstream/123456789/1954/1/A2005-22.pdf"
    - "https://www.indiacode.nic.in/bitstream/123456789/1560/1/A1955-25.pdf"
    - "https://www.indiacode.nic.in/bitstream/123456789/2303/1/A1937-26.pdf"
    - "https://www.indiacode.nic.in/bitstream/123456789/2186/1/A1872-15.pdf"
    - "https://www.indiacode.nic.in/bitstream/123456789/23393/1/P3A1936-2.pdf"
    - "https://www.indiacode.nic.in/bitstream/123456789/15319/1/A1954-43.pdf"

    # ‚öñÔ∏è Landmark Supreme Court Judgments
    - "https://nja.gov.in/Concluded_Programmes/2019-20/SE-05_2019_PPTs/6.LANDMARK%20JUDGMENTS%20OF%20THE%20SUPREME%20COURT%20PLAIN.pdf"
    - "https://www.narcoordindia.gov.in/narcoordindia/judgements.php"
    - "https://misc.manupatra.in/images/Illustrated_cases_supreme_court_of_india.pdf"
    - "https://drive.google.com/file/d/1qCW-xgaA4Nt5g3bskG95N4MKy-SGY54q/view"
    - "https://www.jhalsa.org/pdfs/Reading_Materials/SC_Judgements_FamilyMatters1.pdf"


embeddings:
  model: "all-MiniLM-L6-v2"
  vector_store: "FAISS"
  vector_store_path: "models/vector_store"
  api_key: ""  # not required for local sentence-transformers

llm:
  provider: "groq"
  model: "llama-3.3-70b-versatile"
  api_key: "!secret response_model_API_Key"

